server:
  port: 5501
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    min-spare-threads: 20
    accept-count: 500
    max-connections: 10000
  connection-timeout: 60000
  compression:
    min-response-size: 256
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain,text/css,application/x-javascript

spring:
  quartz:
    job-store-type: jdbc
    # 关闭系统的时候，等待定时任务完成
    wait-for-jobs-to-complete-on-shutdown: false
    # 初始化后是否自动启动计划程序
    auto-startup: true

    jdbc:
      # SQL 初始化脚本中单行注释的前缀
      comment-prefix: --
      # 数据库架构初始化模式--never 从不进行初始化，always 每次都清空数据库进行初始化,embedded 只初始化内存数据库（默认值）
      initialize-schema: always
      # 用于初始化数据库架构的SQL文件的路径
      schema: classpath:sql/quartz/tables_oracle.sql
    properties:
      org:
        quartz:
          scheduler:
            instanceName: NitsmScheduler3
            instanceId: AUTO
          threadPool:
            #实例化ThreadPool时，使用的线程类为SimpleThreadPool
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 30
            #优先级 默认值为5
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
            isClustered: flase
            clusterCheckinInterval: 60000
            useProperties: false

  cache:
    type: ehcache
  application:
    name: nitsm
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  datasource:
    druid:
      url: jdbc:oracle:thin:@192.168.73.26:1521/bhm
      username: jinanv2
      password: jinanv2

      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 8
      maxActive: 20
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 160000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 230000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      keepAlive: true

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 90MB

  thymeleaf:
    servlet:
      content-type: text/html
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates
    suffix: .html

mybatis-plus:
  type-aliases-package: com.jcca.**.entity
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    enable-sql-runner: true
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



jcca:
  redis:
    host: 192.168.73.26
    port: 6379
    password: jcca@123
    timeout: 5000
    database: 7

    jedis:
      pool1:
        max-wait: 1000
        max-total: 50
        min-idle: 5
        max-idle: 20
        minEvictableIdleTimeMillis: 120000      #连接空闲多久后可以被驱逐，单位毫秒
        softMinEvictableIdleTimeMillis: 60000   # 空闲连接驱逐前的检测时间
        numTestsPerEvictionRun: 100             # 测试间隔
        timeBetweenEvictionRunsMillis: 20000    # 20s检查一次
      pool2:                                     # 带事务的redis 缓存池
        max-wait: 1000
        max-total: 50
        min-idle: 5
        max-idle: 20
        minEvictableIdleTimeMillis: 120000      #连接空闲多久后可以被驱逐，单位毫秒
        softMinEvictableIdleTimeMillis: 60000   # 空闲连接驱逐前的检测时间 链接不够用的时候超过1分钟的连接优先释放
        numTestsPerEvictionRun: 100             # 检查链接数量
        timeBetweenEvictionRunsMillis: 20000    # 20s检查一次



logging:
  config: classpath:logback-spring.xml

project:
  captcha-open: false                         #是否开启登录验证码
  base-url: http://127.0.0.1:5501         #访问项目的基础路径
  shiro:
    remember-me-timeout: 30                    #cookie记住登录信息时间，30天（天）
    global-session-timeout: 1296000              #Session会话超时时间，15天（秒）
    seeeion-validation-interval: 18000          #Session会话检测间隔时间，10分钟
    excludes: /api/free/**                      #忽略的路径规则，多个规则使用","逗号隔开
  upload:
    file-path: D://data//upload              #文件上传路径
    static-path: /upload                     #上传文件静态访问路径
    static-url: http://127.0.0.1:5502     #静态文件访问路径
  syslog_snmp:
    host: 192.168.20.66

# 专家知识库
kbUrl:
  192.168.73.210
# 动环地址
dhUrl:
  192.168.1.84

# 3D配置
threeD:
  #组织ID
  orgId: 1456533450382184449
  # 机房ID
  roomId1: 4-110
  # 机房ID2
  roomId2: 4-111
  # 告警数据推送周期
  cron: "*/11 * * * * ?"
  # 接口服务器IP
  rabbitMQhost: 192.168.51.104
  # 接口服务器端口
  rabbitMQPort: 5672
  # 接口服务器用户名
  rabbitMQUsername: root
  # 接口服务器密码
  rabbitMQPassword: 1qaz
  #MQ虚拟机
  rabbitMQVirtual: /


aiConfig:
  cpuStr: 根据以下CPU的运行趋势判断是否有风险点：
  memoryStr: 根据以下内存的运行趋势判断是否有风险点：
  swapStr: 根据以下交换空间的运行趋势判断是否有风险点：
  diskStr: 分析以下磁盘状态：
  processStr: 简单介绍这个进程：
  alarmStr: 分析以下告警，并给出解决方案：
  brokenRecordStr: 分析以下故障并给出建议方案：
  networkCardStr: 分析以下网卡状态：
  alarmListStr: 分析这个设备的告警清单，并给出建议方案
  portStr: 端口