# MONITORING CONFIGURATIONS - PLEASE EDIT WITH CAUTION #

# Determine whether the connection should be started automatically or not.

# Monitoring application will try to start all the connections when it starts. 
# or you will need to manually start the connection from Web UI once the app is started.
# Since 0.2.1
config.connectionAutoStart=true


# A list of notification provider names that are enabled (comma separated values, the name is case-sensitive)
# The default provider name is: default, which is email notification.
# You can provide your own notification provider with your provider name,
# Please DON'T use 'default' as the name, which is reserved. Any invalid provider names
# or any conflicts with another provider names will be ignored.

# e.g. default, email, MQTT, SMS
# If omit, it defaults to the default notification provider named 'default'
# Since 0.2.1
config.notificationProviders=default


########################################################
# Monitor thresholds apply for all the related settings
########################################################
# supported the time unit short names: 
# s - second
# m - minute
# h - hour
# d - day

#support: s|m|h|d
config.monitorPollingIntervalMin=10s
#support: m|h|d
config.monitorSlidingWindowMax=1d
#support: m|h|d
config.monitorDataExpirationTimeMax=7d


########################################################
# Monitor default settings
########################################################
#Data collection interval from QMGRs
#support: s|m|h|d, should >= min defined in the thresholds
config.monitorPollingInterval=10s

#The time range that  statistical data will be visualized on UI
#support: m|h|d, should <= max defined in the thresholds
config.monitorSlidingWindow=1h

#The time that the statistical data will be expired and deleted automatically
#support: m|h|d, should <= max defined in the thresholds
config.monitorDataExpirationTime=1d

########################################################
# MQTT Monitor(topic monitor) default settings
########################################################
#support: s|m|h|d
config.mqttMonitorPollingInterval=10s
#support: m|h|d
config.mqttMonitorSlidingWindow=10m
#support: m|h|d 
config.mqttMonitorDataExpirationTime=1h


########################################################
# QMGR monitor (a.k.a system monitor)
########################################################
#support: s|m|h|d
config.qmgrMonitorPollingInterval=5m
#support: m|h|d
config.qmgrMonitorSlidingWindow=30m
#support: m|h|d
config.qmgrMonitorDataExpirationTime=2h



########################################################
# Monitor default alert condition settings
########################################################
# Alert rule syntax: LDAP filter alike.
# boolean-operator ::= '&' | '|'
# operator ::= > | < | >= | <= | !=
# expr ::= (property operator value)
# alert-rule ::= warn(boolean-operator(expr)(expr)(expr)... ), error(boolean-operator(expr)(expr)(expr)... )

#Default health rules for monitors(validated on startup)
#Customize your own default rules for different objects if needed
#Example rules for queue and topic:

#Means: alert a warning if currentQDepth>1000 or openInputCount>100
#       and alert a error if currentQDepth>30000 and openInputCount>200
#Available properties: 
#--------------------------------------------------------------------------------
#currentQDepth, maxQDepth, occupiedPercent, openInputCount, openOutputCount
#--------------------------------------------------------------------------------
#config.queueHealthRule=warn(|(currentQDepth>1000)(openInputCount>100)), error(&(currentQDepth>30000)(openInputCount>200))

#Means: alert a warning if currentQDepth>1000 and alert a error if currentQDepth>4000
#config.queueHealthRule=warn(currentQDepth>1000), error(currentQDepth>4000)


#Means: alert a warning if publishedMessagesCount>1000
#Available properties: 
#----------------------------------------------------------------
#publishedMessagesCount, publishersCount, subscribersCount
#----------------------------------------------------------------
#config.topicHealthRule=warn(publishedMessagesCount>1000)

#Means: alert a warning if the channelStatus is Stopped
#Available channelStatus values: 
#---------------------------------------------------------------------------------------------------------
# Stopped, Running, Stopping, Inactive, Initializing, Binding, Starting, Paused, Retrying, Requesting
#---------------------------------------------------------------------------------------------------------
config.channelHealthRule=warn(channelStatus=Stopped)

#Means: alert a warning if the listenerStatus is Stopped
#Available listenerStatus values: 
#-----------------------------------------
# Starting, Running, Stopping, Stopped
#-----------------------------------------
config.listenerHealthRule=warn(listenerStatus=Stopped)

#Means: alert a error if the queueManagerStatus is Unavailable
#Available queueManagerStatus values: 
#------------------------------------------------
# Starting, Running, Quiescing, Unavailable
#------------------------------------------------
config.queueManagerHealthRule=warn(queueManagerStatus=Unavailable)



########################################################
# Generic settings
########################################################
#in seconds (using MQ default value 30 seconds if negative or 0)
#Timeout of connecting to the QMGRs
config.monitorConnectionTimeout=10

#The max number of active monitors which is collecting data from QMGRs
#Note: this setting may have impact on the performance of QMGR
#number>0 (no limit: if zero or negative)
config.maxActiveMonitors=0


#The statistical data cache size. It improves the performance when querying statistics
#But it increases the memory consumption, set a proper value according to your needs.
#number>0 (disable cache: if zero or negative)
config.statisticsCacheSize=10000
 
 
#Whether create the default user or not
#default user/password: mqadmin/mqadmin, change it after login
#should be true at the moment, since there is no other way to specify those info.
config.createMonitorDefaultUser=true


#Note: the followings two items are NOT used currently
#if <=0, means auto detected via available processors
#config.numberOfDataWorkers=0
#if <=0, means using default value 10000
#config.dataWorkerQueueCapacity=10000


#The interval to perform a data purge operation (clean the expired data from database)
#support s|m|h|d
config.dataPurgeInterval=30m

#The interval to perform monitor diagnose to check if the monitor is working properly
#and deactivate the monitor automatically if monitor is not working normally according
#to the diagnose thresholds defined below.
#support s|m|h|d
config.monitorDiagnoseInterval=30s

#Diagnose thresholds
#if<=0, means using default value 0.2
#Means: if the monitor data collection failure rate reaches 20%, the monitor will be 
#deactivate automatically (you can activate it again from the UI).
config.diagnoseFailRateThreshold=0.2

#if<=0, means using default value 0.3
#Means: if the monitor data collection timeout rate reaches 30%, the monitor will be 
#deactivate automatically (you can activate it again from the UI).
config.diagnoseTimeoutRateThreshold=0.3

#Means: if the monitor data collection consecutive failures reaches 20 times, the monitor will be 
#deactivate automatically (you can activate it again from the UI).
#means N consecutive failures happen, if<=0, means using default value 20
config.diagnoseConsecutiveFailureThreshold=20

#will not apply diagnose strategy before reach this threshold, even if failure or timeout happens
#if<=0, means using default value 10
config.diagnosableThreshold=10


#The interval that updates the connected MQTT client info
#Use a bigger value to reduce performance impact on MQ if the client is not changing frequently,
#or you don't need the live updates.
#support s|m|h|d
config.mqttConnectionRefreshInterval=10s


#Extensions for the strategy,this will need implement some interfaces of monitoring SPI. 
#Normally, no need to change unless you want to provide your own strategy.
#if left empty or value 'default' default strategy is used
config.monitorDiagnoseStrategy=default

#if left empty or value 'default' default strategy is used
config.monitorScheduleStrategy=default

#The interval to clean the subscription destination queue which is created by the monitoring tool,
#it is used to calculate the message published to the topic. 
#support s|m|h|d
config.subscriptionDestinationCleanInterval=30m


############################ END ############################# 