--端口指标更新--
update PERFORMANCE_TARGET SET TARGET_HANDLE='COLLECT_INTERFACES',TARGET_DESCRIPTION='端口采集',COMMAND = 'pubPortName|pubPortIndex|pubPortType|pubPortPhysAddress|pubPortSpeed|pubPortStatus|pubPortIn|pubPortOut|pubPortDiscardsIn|pubPortDiscardsOut|pubPortMorePointIn|pubPortMorePointOut|pubPortPointIn|pubPortPointOut|pubPortErrorIn|pubPortErrorOut|pubPortIdentifier|pubPortIp|pubPortFCSErrors|pubPortOpticalPower',
COMMAND_NAME = '网络设备端口采集'  where TARGET_HANDLE = 'INTERFACES_CISCO_SNMP';
 
--CPU指标--
update PERFORMANCE_TARGET SET TARGET_HANDLE='CPU_USED_RATE',TARGET_DESCRIPTION='CPU使用率采集',COMMAND = 'H3CNetCpuUsedRate',COMMAND_NAME = 'H3c设备CPU使用率采集' where TARGET_DESCRIPTION LIKE '%H3C路由器CPU%';
update PERFORMANCE_TARGET SET TARGET_HANDLE='CPU_USED_RATE',TARGET_DESCRIPTION='CPU使用率采集',COMMAND = 'N7KNetCpuUsedRate',COMMAND_NAME = 'N7K设备CPU使用率采集' where TARGET_DESCRIPTION LIKE '%N7K交换机CPU%';
update PERFORMANCE_TARGET SET TARGET_HANDLE='CPU_USED_RATE',TARGET_DESCRIPTION='CPU使用率采集',COMMAND = 'pubNetCpuUsedRate',COMMAND_NAME = '思科设备CPU使用率采集' where (TARGET_DESCRIPTION LIKE '%思科交换机CPU%' or TARGET_DESCRIPTION LIKE '%思科路由器CPU%' );
update PERFORMANCE_TARGET SET TARGET_HANDLE='CPU_USED_RATE',TARGET_DESCRIPTION='CPU使用率采集',COMMAND = 'pubWinCpuUsedRate',COMMAND_NAME = 'windows设备CPU使用率采集' where TARGET_HANDLE = 'CPU_WIN_SNMP';
update PERFORMANCE_TARGET SET TARGET_HANDLE='CPU_USED_RATE',TARGET_DESCRIPTION='CPU使用率采集',COMMAND = 'vmStatLinuxCpuUsedRate',COMMAND_NAME = 'linux设备CPU使用率采集' where TARGET_HANDLE = 'CPU_LINUX_SSH_VMSTAT';
update PERFORMANCE_TARGET SET TARGET_HANDLE='CPU_USED_RATE',TARGET_DESCRIPTION='CPU使用率采集',COMMAND = 'pubAixCpuUsedRate',COMMAND_NAME = 'AIX设备CPU使用率采集' where TARGET_HANDLE = 'CPU_AIX_SSH';
update PERFORMANCE_TARGET SET TARGET_HANDLE='CPU_USED_RATE',TARGET_DESCRIPTION='CPU使用率采集',COMMAND = 'huaWeiNetCpuUsedRate',COMMAND_NAME = '华为网络设备CPU使用率采集' where TARGET_HANDLE = 'CPU_HUAWEI_SWITCH';
 
--内存指标--
update PERFORMANCE_TARGET SET TARGET_HANDLE='MEMORY_USED_RATE_COLLECT',TARGET_DESCRIPTION='内存使用率采集',COMMAND = 'netH3cUsedMemory|netH3cTotalMemory',COMMAND_NAME = 'H3C网络设备内存采集' where TARGET_HANDLE = 'MEMORY_CISCO_SNMP' and TARGET_DESCRIPTION like '%H3C%';
update PERFORMANCE_TARGET SET TARGET_HANDLE='MEMORY_USED_RATE_COLLECT',TARGET_DESCRIPTION='内存使用率采集',COMMAND = 'netN7kMemoryUsed|netN7kMemoryFree',COMMAND_NAME = 'N7K网络设备内存采集' where TARGET_HANDLE = 'MEMORY_CISCO_SNMP' and TARGET_DESCRIPTION like '%N7K%';
update PERFORMANCE_TARGET SET TARGET_HANDLE='MEMORY_USED_RATE_COLLECT',TARGET_DESCRIPTION='内存使用率采集',COMMAND = 'netPubUsedMemory|netPubFreeMemory',COMMAND_NAME = '思科网络设备内存采集' where TARGET_HANDLE = 'MEMORY_CISCO_SNMP' and TARGET_DESCRIPTION like '%思科%';
update PERFORMANCE_TARGET SET TARGET_HANDLE='MEMORY_USED_RATE_COLLECT',TARGET_DESCRIPTION='内存使用率采集',COMMAND = 'windowsPubMemory',COMMAND_NAME = 'windows设备内存采集' where TARGET_HANDLE = 'MEMORY_WIN_SNMP';
update PERFORMANCE_TARGET SET TARGET_HANDLE='MEMORY_USED_RATE_COLLECT',TARGET_DESCRIPTION='内存使用率采集',COMMAND = 'linuxPubMemory',COMMAND_NAME = 'linux设备内存采集' where TARGET_HANDLE = 'MEMORY_LINUX_SSH';
update PERFORMANCE_TARGET SET TARGET_HANDLE='MEMORY_USED_RATE_COLLECT',TARGET_DESCRIPTION='内存使用率采集',COMMAND = 'aixPubMemory',COMMAND_NAME = 'aix设备内存采集' where TARGET_HANDLE = 'MEMORY_AIX_SSH';
update PERFORMANCE_TARGET SET TARGET_HANDLE='MEMORY_USED_RATE_COLLECT',TARGET_DESCRIPTION='内存使用率采集',COMMAND = 'netHuaweiMemory',COMMAND_NAME = '华为设备内存采集' where TARGET_HANDLE = 'MEMORY_HUAWEI_SWITCH';
 
--温度--
UPDATE PERFORMANCE_TARGET SET TARGET_HANDLE = 'SNMP_SENSOR',COMMAND = 'netSensorPub',COMMAND_NAME='网络设备通用温度采集' where TARGET_DESCRIPTION = '交换机传感器检测' or TARGET_DESCRIPTION = '路由器传感器检测';
UPDATE PERFORMANCE_TARGET SET TARGET_HANDLE = 'SNMP_SENSOR',COMMAND = 'netSensorN7K',COMMAND_NAME='N7K网络设备温度采集' where TARGET_DESCRIPTION = '思科N7K交换机温度采集';
UPDATE PERFORMANCE_TARGET SET TARGET_HANDLE = 'SNMP_SENSOR',COMMAND = 'netSensorH3C',COMMAND_NAME='H3C网络设备温度采集' where TARGET_DESCRIPTION = 'H3CK交换机温度采集';
UPDATE PERFORMANCE_TARGET SET TARGET_HANDLE = 'SNMP_SENSOR',COMMAND = 'netSensorHuaWei',COMMAND_NAME='华为网络设备温度采集' where TARGET_DESCRIPTION = '华为交换机温度采集';
 
--管理口--
UPDATE PERFORMANCE_TARGET SET TARGET_HANDLE = 'SYS_PORT_SERVER' , COMMAND ='immUserPwd' WHERE TARGET_DESCRIPTION like '%管理口%';